# Generated by Django 4.0.3 on 2022-03-28 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.category'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='Discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producer',
            name='lprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producer',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
