# Generated by Django 4.0.3 on 2022-04-09 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_producer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='Category',
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='pages.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='pcategory',
            field=models.ForeignKey(limit_choices_to={'pcategory_isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.category'),
        ),
    ]
