# Generated by Django 4.0.3 on 2022-04-09 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_brand_category_brand_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pcategory',
            field=models.ForeignKey(blank=True, limit_choices_to={'pcategory_isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.category'),
        ),
    ]
