# Generated by Django 4.0.3 on 2022-06-25 10:58

from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_pcategory_alter_category_pcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.order')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('Product_number', models.IntegerField(unique=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('lprice', models.IntegerField(blank=True, null=True)),
                ('Discount', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(upload_to=pages.models.product_image_upload)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='img',
            field=models.ImageField(default='img.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcategory',
            name='img',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='producer',
        ),
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.category'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.product'),
        ),
    ]
