# Generated by Django 4.0.3 on 2022-07-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=250, null=True)),
                ('internal_memory', models.CharField(blank=True, max_length=250, null=True)),
                ('model_color', models.CharField(blank=True, max_length=250, null=True)),
                ('sim_nm', models.IntegerField(blank=True, null=True)),
                ('g_type', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('Product_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('Brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.brand')),
            ],
        ),
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phones', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.phones')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='category',
            name='pcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.pcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='product'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='pproduct',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='Pproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.pproduct'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.types'),
        ),
    ]
