# Generated by Django 4.0.3 on 2022-07-10 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('pages', '0017_alter_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='phones',
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.types'),
        ),
        migrations.DeleteModel(
            name='phones',
        ),
        migrations.DeleteModel(
            name='types',
        ),
    ]
