# Generated by Django 4.0.3 on 2022-07-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_remove_types_phones_alter_product_type_delete_phones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
