# Generated by Django 4.0.3 on 2022-07-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_brand_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rel_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
