# Generated by Django 4.0.6 on 2022-07-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_product_rel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pproduct',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
