# Generated by Django 4.0.6 on 2022-07-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_rename_name_category_ar_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
