# Generated by Django 4.0.6 on 2022-07-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pproduct',
            name='suggested_products',
            field=models.ManyToManyField(to='pages.product'),
        ),
    ]
