# Generated by Django 4.0.6 on 2022-07-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_pproduct_suggested_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='secondary_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_image',
            field=models.ManyToManyField(to='pages.secondary_image'),
        ),
    ]
