# Generated by Django 4.0.6 on 2022-07-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_secondary_image_product_secondary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='product'),
        ),
        migrations.AlterField(
            model_name='secondary_image',
            name='img',
            field=models.ImageField(upload_to='product'),
        ),
    ]
