# Generated by Django 4.0.6 on 2022-07-22 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_product_img_alter_secondary_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='secondary_image',
            field=models.ManyToManyField(max_length=3, to='pages.secondary_image'),
        ),
        migrations.AlterField(
            model_name='secondary_image',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
