# Generated by Django 4.0.6 on 2022-07-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_alter_secondary_image_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ar_name',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
