# Generated by Django 4.0.6 on 2022-07-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_category_similar_category_alter_product_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='similar_category',
        ),
        migrations.AddField(
            model_name='category',
            name='similar_category',
            field=models.ManyToManyField(blank=True, null=True, to='pages.category'),
        ),
    ]
