# Generated by Django 4.0.6 on 2022-07-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_remove_category_similar_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcategory',
            name='similar_Pcategory',
            field=models.ManyToManyField(blank=True, to='pages.pcategory'),
        ),
        migrations.AlterField(
            model_name='category',
            name='similar_category',
            field=models.ManyToManyField(blank=True, to='pages.category'),
        ),
    ]
