# Generated by Django 4.0.6 on 2022-07-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_pcategory_similar_pcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcategory',
            name='similar_Pcategory',
        ),
        migrations.AddField(
            model_name='pcategory',
            name='similar_Pcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.pcategory'),
        ),
    ]
