# Generated by Django 4.0.6 on 2022-07-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_remove_pcategory_similar_pcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=0),
            preserve_default=False,
        ),
    ]
