# Generated by Django 4.0.3 on 2022-07-10 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=250, null=True)),
                ('internal_memory', models.CharField(blank=True, max_length=250, null=True)),
                ('model_color', models.CharField(blank=True, max_length=250, null=True)),
                ('sim_nm', models.IntegerField(blank=True, null=True)),
                ('g_type', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phones', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.phones')),
            ],
        ),
    ]
