# Generated by Django 4.0.3 on 2022-07-15 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_product_type'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[], max_length=250)),
                ('phones', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.phones')),
            ],
        ),
        migrations.DeleteModel(
            name='types',
        ),
    ]
