# Generated by Django 4.0.3 on 2022-07-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_det_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='det_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
