# Generated by Django 4.0.6 on 2022-07-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_phones_det_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='img',
            field=models.ImageField(default=' ', upload_to='product'),
            preserve_default=False,
        ),
    ]
