# Generated by Django 4.0.6 on 2022-07-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_phones_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
