# Generated by Django 4.0.6 on 2022-07-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_airbods_alter_det_type_det_airbods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbods',
            name='img',
            field=models.ImageField(upload_to='product'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='img',
            field=models.ImageField(upload_to='product'),
        ),
    ]
